# Generated by Django 5.0.6 on 2025-09-21 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_user_type_user_role_alter_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='points',
        ),
    ]
