# Generated by Django 5.0.6 on 2025-09-21 13:37

import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DrillScenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Scenario title', max_length=200)),
                ('description', models.TextField(help_text='Scenario description')),
                ('region_tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, help_text='Regions where this scenario is relevant', size=None)),
                ('json_tree', models.JSONField(help_text='Decision tree structure in JSON format')),
                ('difficulty_level', models.CharField(choices=[('BEGINNER', 'Beginner'), ('INTERMEDIATE', 'Intermediate'), ('ADVANCED', 'Advanced')], default='BEGINNER', help_text='Difficulty level of the scenario', max_length=20)),
                ('estimated_duration', models.PositiveIntegerField(default=5, help_text='Estimated duration in minutes')),
                ('max_score', models.PositiveIntegerField(default=100, help_text='Maximum possible score for this scenario')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this scenario is available for attempts')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Drill Scenario',
                'verbose_name_plural': 'Drill Scenarios',
                'db_table': 'drill_scenarios',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DrillAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(default=0, help_text='Score achieved in this attempt', validators=[django.core.validators.MinValueValidator(0)])),
                ('responses', models.JSONField(default=dict, help_text='User responses and path taken through the scenario')),
                ('completed', models.BooleanField(default=False, help_text='Whether the attempt was completed')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(help_text='User who attempted the drill', on_delete=django.db.models.deletion.CASCADE, related_name='drill_attempts', to=settings.AUTH_USER_MODEL)),
                ('scenario', models.ForeignKey(help_text='Scenario that was attempted', on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='drills.drillscenario')),
            ],
            options={
                'verbose_name': 'Drill Attempt',
                'verbose_name_plural': 'Drill Attempts',
                'db_table': 'drill_attempts',
                'ordering': ['-started_at'],
                'unique_together': {('user', 'scenario', 'started_at')},
            },
        ),
    ]
