# Generated by Django 5.0.6 on 2025-09-21 13:37

import django.contrib.postgres.fields
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Alert title', max_length=200)),
                ('description', models.TextField(help_text='Detailed alert description')),
                ('region_tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, help_text='Regions affected by this alert', size=None)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', help_text='Severity level of the alert', max_length=20)),
                ('source', models.CharField(default='NDMA', help_text='Source of the alert (NDMA, IMD, etc.)', max_length=100)),
                ('geometry', models.JSONField(blank=True, help_text='GeoJSON geometry for mapping', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this alert is currently active')),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When the alert was published')),
                ('expires_at', models.DateTimeField(blank=True, help_text='When the alert expires (optional)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Alert',
                'verbose_name_plural': 'Alerts',
                'db_table': 'alerts',
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(help_text='Expo push notification token', max_length=255, unique=True)),
                ('platform', models.CharField(choices=[('ios', 'iOS'), ('android', 'Android'), ('web', 'Web')], help_text='Device platform', max_length=20)),
                ('device_name', models.CharField(blank=True, help_text='User-friendly device name', max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this device is active for notifications')),
                ('last_used', models.DateTimeField(auto_now=True, help_text='Last time this device was used')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(help_text='User who owns this device', on_delete=django.db.models.deletion.CASCADE, related_name='devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Device',
                'verbose_name_plural': 'Devices',
                'db_table': 'devices',
                'ordering': ['-last_used'],
                'unique_together': {('user', 'token')},
            },
        ),
    ]
