# Generated by Django 5.0.6 on 2025-09-21 12:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Module title', max_length=200)),
                ('description', models.TextField(help_text='Module description')),
                ('disaster_type', models.CharField(choices=[('EARTHQUAKE', 'Earthquake'), ('FLOOD', 'Flood'), ('FIRE', 'Fire'), ('CYCLONE', 'Cyclone'), ('OTHER', 'Other')], help_text='Type of disaster this module covers', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(help_text='User who created this module', on_delete=django.db.models.deletion.CASCADE, related_name='created_modules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Learning Module',
                'verbose_name_plural': 'Learning Modules',
                'db_table': 'learning_modules',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Quiz title', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Quiz description', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('module', models.OneToOneField(help_text='Module this quiz belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='quiz', to='learning.module')),
            ],
            options={
                'verbose_name': 'Quiz',
                'verbose_name_plural': 'Quizzes',
                'db_table': 'learning_quizzes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Lesson title', max_length=200)),
                ('content', models.TextField(help_text='Lesson content (Markdown supported)')),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of lesson within module')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('module', models.ForeignKey(help_text='Module this lesson belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='learning.module')),
            ],
            options={
                'verbose_name': 'Lesson',
                'verbose_name_plural': 'Lessons',
                'db_table': 'learning_lessons',
                'ordering': ['order', 'created_at'],
                'unique_together': {('module', 'order')},
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Question text')),
                ('option_a', models.CharField(help_text='Option A', max_length=500)),
                ('option_b', models.CharField(help_text='Option B', max_length=500)),
                ('option_c', models.CharField(help_text='Option C', max_length=500)),
                ('option_d', models.CharField(help_text='Option D', max_length=500)),
                ('correct_option', models.CharField(choices=[('A', 'Option A'), ('B', 'Option B'), ('C', 'Option C'), ('D', 'Option D')], help_text='Correct answer option', max_length=1)),
                ('explanation', models.TextField(blank=True, help_text='Explanation for the correct answer', null=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of question within quiz')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quiz', models.ForeignKey(help_text='Quiz this question belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='learning.quiz')),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
                'db_table': 'learning_questions',
                'ordering': ['order', 'created_at'],
                'unique_together': {('quiz', 'order')},
            },
        ),
    ]
